version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password_for_insurance_tariffs_db
      POSTGRES_DB: insurance_tariffs
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
      DATABASE_URL: postgresql://user:password_for_insurance_tariffs_db@db/insurance_tariffs
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  db_data:
